# Generated by Django 4.2 on 2026-06-26 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=20)),
                ('commodity_mnemonic', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('placeholder', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('post_date', models.DateField()),
                ('enter_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
            options={
                'ordering': ['-post_date', '-enter_date'],
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('memo', models.CharField(blank=True, max_length=2048)),
                ('value_num', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconcile_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='ledger.transaction')),
            ],
            options={
                'ordering': ['transaction__post_date'],
            },
        ),
    ]
