# Generated by Django 4.2 on 2026-06-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default='en', max_length=5)),
                ('date_format', models.CharField(choices=[('%Y-%m-%d', 'YYYY-MM-DD  (2026-01-31)'), ('%d/%m/%Y', 'DD/MM/YYYY  (31/01/2026)'), ('%m/%d/%Y', 'MM/DD/YYYY  (01/31/2026)'), ('%d.%m.%Y', 'DD.MM.YYYY  (31.01.2026)'), ('%d %b %Y', 'DD Mon YYYY  (31 Jan 2026)')], default='%Y-%m-%d', max_length=20)),
                ('decimal_separator', models.CharField(choices=[('.', 'Period  1,234.56'), (',', 'Comma   1.234,56')], default='.', max_length=1)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('currency_before', models.BooleanField(default=True, help_text='Show currency symbol before the amount')),
                ('accent_color', models.CharField(choices=[('#3d8ef8', 'Blue'), ('#3cb66e', 'Green'), ('#9b59b6', 'Purple'), ('#e67e22', 'Orange'), ('#e05252', 'Red'), ('#16a085', 'Teal')], default='#3d8ef8', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
