# Generated by Django 4.2 on 2026-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='commodity_namespace',
            field=models.CharField(choices=[('CURRENCY', 'Currency'), ('SECURITY', 'Security')], default='CURRENCY', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='smallest_fraction',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('BANK', 'Bank'), ('CASH', 'Cash'), ('RECEIVABLE', 'Receivable'), ('STOCK', 'Stock'), ('MUTUAL', 'Fund'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('LIABILITY', 'Liability'), ('CREDIT', 'Credit Card'), ('PAYABLE', 'Payable'), ('EXPENSE', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='commodity_mnemonic',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='accent_color',
            field=models.CharField(choices=[('#4a9238', 'Green'), ('#3d8ef8', 'Blue'), ('#9b59b6', 'Purple'), ('#e67e22', 'Orange'), ('#e05252', 'Red'), ('#16a085', 'Teal')], default='#4a9238', max_length=7),
        ),
    ]
