# Generated by Django 4.2 on 2026-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_account_code_account_commodity_namespace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_namespace', models.CharField(default='CURRENCY', max_length=20)),
                ('commodity_mnemonic', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('value_num', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(default='automatic', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='split',
            name='quantity_num',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['commodity_mnemonic', 'currency', 'date'], name='ledger_pric_commodi_ef1651_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('commodity_mnemonic', 'currency', 'date')},
        ),
    ]
