# Generated by Django 4.2 on 2026-06-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_split_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='commodity_mnemonic',
            field=models.CharField(default='EUR', max_length=32),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=32),
        ),
    ]
