# Generated by Django 4.2 on 2026-06-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_import_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_api_key', models.CharField(blank=True, help_text='API key for a paid exchange-rate provider (leave blank to use the free Frankfurter API)', max_length=200)),
                ('exchange_rate_provider', models.CharField(blank=True, choices=[('frankfurter', 'Frankfurter (free, no key needed)'), ('exchangeratesapi', 'ExchangeRatesAPI.io (key required)'), ('openexchangerates', 'Open Exchange Rates (key required)')], default='frankfurter', max_length=50)),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=False, help_text='Allow new users to self-register')),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
