# Generated by Django 4.2 on 2026-06-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='show_hidden_accounts',
            field=models.BooleanField(default=False, help_text='Show hidden accounts in account pickers'),
        ),
    ]
