# Generated by Django 4.2 on 2026-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_show_hidden_accounts_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('gnucash', 'GnuCash file'), ('fineco', 'Fineco statement (PDF)')], default='gnucash', max_length=20),
        ),
    ]
