# Generated by Django 4.2 on 2026-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_importjob_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('gnucash', 'GnuCash file'), ('fineco', 'Fineco statement (PDF)'), ('amex', 'American Express statement (PDF)')], default='gnucash', max_length=20),
        ),
    ]
