from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('account/<int:account_id>/', views.account_register, name='account_register'),
    path('import/', views.import_gnucash, name='import_gnucash'),
    path('import/<int:job_id>/', views.import_job_status, name='import_job_status'),
    path('import/<int:job_id>/progress/', views.import_job_progress, name='import_job_progress'),
    path('preferences/', views.preferences, name='preferences'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.system_settings, name='system_settings'),
    path('transaction/<int:txn_id>/edit/', views.transaction_edit, name='transaction_edit'),
    path('transaction/<int:txn_id>/delete/', views.transaction_delete, name='transaction_delete'),
    path('transaction/<int:txn_id>/duplicate/', views.transaction_duplicate, name='transaction_duplicate'),
    path('account/<int:account_id>/rows/', views.account_register_rows, name='account_register_rows'),
    path('account/<int:account_id>/new/', views.transaction_new, name='transaction_new'),
    path('account/<int:account_id>/autocomplete/', views.transaction_autocomplete, name='transaction_autocomplete'),
    path('account/<int:account_id>/reconcile/start/', views.reconcile_start, name='reconcile_start'),
    path('account/<int:account_id>/reconcile/', views.reconcile_view, name='reconcile_view'),
    path('account/<int:account_id>/reconcile/done/', views.reconcile_done, name='reconcile_done'),
    path('account/<int:account_id>/reconcile/postpone/', views.reconcile_postpone, name='reconcile_postpone'),
    path('account/<int:account_id>/reconcile/cancel/', views.reconcile_cancel, name='reconcile_cancel'),
    path('split/<int:split_id>/toggle-confirmed/', views.split_toggle_confirmed, name='split_toggle_confirmed'),
    path('split/<int:split_id>/unreconcile/', views.split_unreconcile, name='split_unreconcile'),
    path('accounts/', views.accounts_overview, name='accounts_overview'),
    path('prices/', views.price_list, name='price_list'),
    path('prices/update/', views.update_prices_ajax, name='update_prices_ajax'),
    path('api/exchange-rate/', views.exchange_rate_api, name='exchange_rate_api'),
    path('accounts/new/', views.account_new, name='account_new'),
    path('accounts/<int:account_id>/edit/', views.account_edit, name='account_edit'),
    path('reports/networth/', views.networth_report, name='networth_report'),
    path('reports/networth/data/', views.networth_report_data, name='networth_report_data'),
    path('reports/income/', views.income_report, name='income_report'),
    path('reports/income/data/', views.income_report_data, name='income_report_data'),
    path('reports/expense/', views.expense_report, name='expense_report'),
    path('reports/expense/data/', views.expense_report_data, name='expense_report_data'),
    path('reports/saved/', views.saved_reports, name='saved_reports'),
    path('reports/integrity/', views.integrity_report, name='integrity_report'),
]
